version: '3.8'
name: calculator-app

services:
  api-calculator:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: api-calculator
    ports:
      - "5000:5000"
    networks:
      - calculator

  web-calculator:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: web-calculator
    environment:
      - REMOTE_SERVER_ADDRESS=http://api-calculator:5000
      - NGINX_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - calculator

networks:
  calculator:
    driver: bridge
