name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r BE/requirements.txt

      - name: List installed packages
        run: |
          pip list

      - name: Start REST API
        run: |
          python BE/calculator.py --rest &
          sleep 10  # Adjust if necessary to ensure API is fully started

      - name: Run tests
        run: |
          python -m pytest --junit-xml=report.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # Ensures the report is published regardless of test success or failure
        with:
          report_paths: "report.xml"

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: judevops.azurecr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t judevops.azurecr.io/ahmed_elhasan1-calculator ./BE

      - name: Push Docker image
        run: |
          docker push judevops.azurecr.io/ahmed_elhasan1-calculator:latest

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
